[package]
name = "musidex-daemon"
version = "0.1.0"
authors = ["Paris Douady <paris.douady@adevinta.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
