[package]
name = "musidex-daemon"
version = "0.1.0"
authors = ["Paris Douady <paris.douady@adevinta.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.0-beta.8"
env_logger = "0.8"
include_dir = "0.6"
thiserror = "1.0"
sqlx = { version = "0.5", default-features = false, features = [ "runtime-actix-rustls", "postgres" ] }
log = "0.4.14"