name: flutter_audio_service_demo
description: Companion project for tutorial on audio_service plugin.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audio_video_progress_bar: ^1.0.0
  get_it: ^7.2.0

dev_dependencies:
  flutter_lints: any
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "musidex_logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true